spring:
  application:
    name: codechampion-codesandbox
server:
  port: 8082
codesandbox:
  compile-config:
    java-class-name: Main.java
  docker:
    auto-pull-images: true
    default-images:
      - openjdk:8-alpine

