spring:
  application:
    name: codechampion-codesandbox
server:
  port: 8082
codesandbox:
  compile-config:
    java-class-name: Main.java
    timeout: 5000
  docker:
    # 若 docker中没有对应 default-image 则会自动拉取
    auto-pull-images: true
    default-images:
      - openjdk:8-alpine

